import React,{useEffect,useState} from 'react';
import {Box,Sun,Moon,RefreshCw,Radio} from 'lucide-react';
import {useTheme} from '../context/ThemeContext';
export default function Header({activeStation,onStationChange,connectionStatus,activeAlertCount,onManualSync,isSyncing,onViewChange}){
 const {isDark,toggleTheme}=useTheme();const [now,setNow]=useState(()=>new Date());const [solar,setSolar]=useState(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);
 const utc=now.toLocaleTimeString('en-GB',{timeZone:'UTC',hour12:false});const ist=now.toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata',hour12:false});
 const longitude=activeStation==='maitri'?11.7358:76.1872;const lmt=new Date(now.getTime()+longitude*4*60000).toLocaleTimeString('en-GB',{timeZone:'UTC',hour12:false});
 return <header className="desk-app-header"><div className="desk-brand"><Radio size={21}/><span>Polar station operations<small>India’s Antarctic research stations · Prototype</small></span></div><div className="desk-header-stations" aria-label="Select station">{['maitri','bharati'].map(slug=><button key={slug} aria-pressed={slug===activeStation} onClick={()=>onStationChange(slug)}>{slug==='maitri'?'Maitri':'Bharati'}</button>)}</div><div className="desk-header-tools"><span className="desk-header-clock">{utc} UTC</span><button className="desk-clock-toggle" title="Switch between Indian Standard Time and local mean solar time" onClick={()=>setSolar(v=>!v)}>{solar?lmt:ist} {solar?'LMT':'IST'}</button><button onClick={()=>onViewChange?.('twin')} title="Open 3D digital twin" aria-label="Open 3D digital twin"><Box size={18}/></button><button onClick={onManualSync} disabled={isSyncing} title="Sync weather" aria-label="Sync weather"><RefreshCw size={17} className={isSyncing?'animate-spin':''}/></button><button onClick={toggleTheme} title={isDark?'Use light theme':'Use dark theme'} aria-label={isDark?'Use light theme':'Use dark theme'}>{isDark?<Sun size={18}/>:<Moon size={18}/>}</button><span className="desk-header-connection" title={connectionStatus}><i style={{background:connectionStatus==='LIVE'?'var(--good)':'var(--signal)'}}/>{activeAlertCount>0?`${activeAlertCount} alerts`:connectionStatus==='LIVE'?'Connected':'Connecting'}</span></div></header>;
}
