import Status from './dashboard/Status';
import React,{useState} from 'react';
import {displayNumber as n} from './dashboard/data';
export default function MlDiagnosticsCard({telemetry}){
 const [mode,setMode]=useState('ALL');const ml=telemetry?.ml_diagnostics;const forecast=telemetry?.fuel_forecast;const factors=ml?.contributing_factors||[];
 if(!ml)return <section className="desk-panel"><h2>Model analysis</h2><p className="desk-empty">No model output received yet.</p></section>;
 const score=ml.anomaly_pct??(ml.anomaly_score!=null?ml.anomaly_score*100:null);const critical=ml.classification!=='NOMINAL_HEALTH';
 return <section className="desk-panel"><div className="desk-panel-heading"><div><h2>Experimental model analysis</h2><p>Isolation Forest scores simulated sensor patterns. An anomaly score is not a calibrated probability of equipment failure.</p></div><Status warning={critical}>{(ml.classification||'Unavailable').replaceAll('_',' ').toLowerCase()}</Status></div><div className="desk-analysis-grid"><article className="desk-reading"><h3>Model health index</h3><strong>{n(ml.health_index)}%</strong><p>Derived from the anomaly score; this is not an independent station health measurement.</p></article><article className="desk-reading"><h3>Anomaly score</h3><strong>{n(score)}%</strong><p>Higher scores represent greater deviation from the model’s baseline.</p></article><article className="desk-reading"><h3>Reported model confidence</h3><strong>{n(ml.confidence==null?null:ml.confidence*100,0)}%</strong><p>Backend confidence indicator. Validation against real station outcomes is unavailable.</p></article></div><div className="desk-note" style={{marginTop:24}}>Fuel model: {n(forecast?.projected_7day_consumption_l,0)} L projected over 7 days. The complete daily projection is in Logistics.</div><div className="desk-config"><div className="desk-panel-heading"><div><h2>Contributing sensor deviations</h2><p>Current readings compared with the model baseline.</p></div></div>{factors.length?<><div className="desk-subnav" aria-label="Deviation display">{[['ALL','Both'],['PCT','Percentage'],['VALUE','Absolute value']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div><div className="desk-reading-grid">{factors.map((factor,i)=><article className="desk-reading" key={factor.sensor||i}><h3 className="desk-reading-label">{factor.label||factor.sensor||'Sensor'}</h3><p>Current: {n(factor.current_value)} {factor.unit} · Baseline: {n(factor.baseline_mean)} {factor.unit}</p>{mode!=='VALUE'&&<p>Deviation: {factor.delta_pct_str??`${n(factor.delta_pct)}%`}</p>}{mode!=='PCT'&&<p>Absolute change: {factor.delta_val_str??`${n(factor.delta_val)} ${factor.unit||''}`}</p>}<p>Z score: {factor.z_score_str??n(factor.z_score)}{factor.impact?` · ${factor.impact}`:''}</p></article>)}</div></>:<p className="desk-muted">No contributing sensor deviations are reported for the current snapshot.</p>}</div></section>;
}
