import Status from './dashboard/Status';
import React, {useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {displayNumber as n,systemLabels,systemState} from './dashboard/data';
const groups={energy:['POWER_CHP','BATTERY_STORAGE'],infrastructure:['WATER_INTAKE','HVAC_GLYCOL','STRUCTURAL_HEALTH'],environment:['WEATHER'],all:['POWER_CHP','BATTERY_STORAGE','WATER_INTAKE','HVAC_GLYCOL','FUEL_STORAGE','STRUCTURAL_HEALTH','WEATHER']};
export default function SubsystemTabs({telemetry,onSelectSubsystem,group='all'}){
 const systems=(telemetry?.subsystems||[]).filter(s=>(groups[group]||groups.all).includes(s.code)).sort((a,b)=>(groups[group]||groups.all).indexOf(a.code)-(groups[group]||groups.all).indexOf(b.code));
 const [selected,setSelected]=useState(null);const system=systems.find(s=>s.code===selected)||systems[0];
 if(!system)return <div className="desk-empty" role="status">No system data is available yet. The station connection retries automatically.</div>;
 const state=systemState(system,telemetry);
 return <section className="desk-panel"><nav className="desk-subnav" aria-label="Subsystem selection">{systems.map(s=><button key={s.code} aria-pressed={system.code===s.code} onClick={()=>setSelected(s.code)}>{systemLabels[s.code]||s.name}</button>)}</nav><div className="desk-panel-heading"><div><h2>{systemLabels[system.code]||system.name}</h2><p>{system.name} · Simulated sensor readings</p></div><Status warning={state!=='Nominal'}>{state}</Status></div><div className="desk-reading-grid">{(system.sensors||[]).map(sensor=><article className={`desk-reading ${sensor.is_anomaly?'is-warning':''}`} key={sensor.sensor_code}><div className="desk-reading-label">{sensor.name}</div><strong>{n(sensor.current_value,sensor.unit==='state'?0:1)}<small>{sensor.unit}</small></strong><Status warning={sensor.is_anomaly}>{!Number.isFinite(sensor.current_value)?'Unavailable':sensor.is_anomaly?'Outside configured range':'Within configured range'}</Status><p>Configured range: {n(sensor.safe_min)}–{n(sensor.safe_max)} {sensor.unit}</p></article>)}</div>{!system.sensors?.length&&<p className="desk-empty">No sensors are configured for this system.</p>}<div className="desk-exercise-footer"><p className="desk-muted">Ranges and equipment metadata belong to this prototype’s configuration.</p><button className="desk-link" onClick={()=>onSelectSubsystem(system.code)}>Open sensor diagnostics<ArrowUpRight size={16}/></button></div><details className="desk-config"><summary>Prototype equipment configuration</summary><p className="desk-muted">{system.description}</p><dl>{Object.entries(system.telemetry_metadata||{}).map(([key,value])=><React.Fragment key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value)}</dd></React.Fragment>)}</dl></details></section>;
}
