import React,{useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {useTheme} from '../context/ThemeContext';
const channels=[['power_kw','Power generation','kW'],['fuel_burn_lh','Fuel consumption','L/h'],['thermal_temp','Thermal supply','°C']];
export default function TelemetryCharts({history=[],stationSlug}){
 const [channel,setChannel]=useState('power_kw');const {isDark}=useTheme();const [,label,unit]=channels.find(c=>c[0]===channel);
 const title=channel==='thermal_temp'?(stationSlug==='maitri'?'Water pipeline temperature':'Glycol supply temperature'):label;
 return <section className="desk-panel"><div className="desk-panel-heading"><div><h2>Recent station readings</h2><p>Latest {history.length} samples · Generated demonstration history and incoming simulator readings. Time labels are UTC.</p></div></div><div className="desk-subnav" aria-label="Trend signal">{channels.map(([id,name])=><button key={id} aria-pressed={id===channel} onClick={()=>setChannel(id)}>{id==='thermal_temp'?(stationSlug==='maitri'?'Water temperature':'Heating temperature'):name}</button>)}</div><p className="desk-muted">{title} / {unit}</p><div className="desk-chart-frame">{!history.length?<div className="desk-empty" role="status">Waiting for history. New readings appear as telemetry arrives.</div>:<ResponsiveContainer width="100%" height="100%"><LineChart data={history} margin={{top:20,right:20,left:0,bottom:10}}><CartesianGrid stroke={isDark?'#536866':'#9ba9a4'} strokeDasharray="3 5" vertical={false}/><XAxis dataKey="time" tick={{fontSize:11}} minTickGap={45} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} domain={['auto','auto']} axisLine={false} tickLine={false} width={55}/><Tooltip formatter={value=>[`${value} ${unit}`,title]} contentStyle={{background:isDark?'#303d3f':'#e4e8e5',border:'1px solid #9ba9a4',color:isDark?'#e1e8e1':'#192629',fontSize:12}}/><Line dataKey={channel} type="monotone" stroke={isDark?'#a3c8d1':'#345d6b'} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>}</div></section>;
}
