# Generated by Django 6.1 on 2026-09-30 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(help_text='Elevation above sea level in meters')),
                ('location_name', models.CharField(max_length=128)),
                ('operational_status', models.CharField(choices=[('NOMINAL', 'Nominal / Fully Operational'), ('DEGRADED', 'Degraded / Non-critical Issue'), ('CRITICAL', 'Critical / Alarm Active'), ('EMERGENCY', 'Emergency / Katabatic High Threat')], default='NOMINAL', max_length=16)),
                ('commissioning_year', models.PositiveIntegerField()),
                ('active_crew_count', models.PositiveIntegerField(default=24)),
                ('description', models.TextField(blank=True)),
                ('ambient_temp', models.FloatField(default=-15.0, help_text='Outdoor dry bulb temp (°C)')),
                ('wind_speed', models.FloatField(default=25.0, help_text='Wind speed (km/h)')),
                ('wind_direction', models.FloatField(default=120.0, help_text='Wind direction (degrees)')),
                ('surface_pressure', models.FloatField(default=985.0, help_text='Surface pressure (hPa)')),
                ('solar_radiation', models.FloatField(default=0.0, help_text='Direct solar radiation (W/m²)')),
                ('weather_condition', models.CharField(default='Overcast / Drifting Snow', max_length=64)),
                ('last_weather_sync', models.DateTimeField(blank=True, null=True)),
                ('total_power_kw', models.FloatField(default=280.0)),
                ('fuel_reserve_days', models.FloatField(default=185.0)),
                ('primary_thermal_temp', models.FloatField(default=60.0)),
                ('active_alert_count', models.PositiveIntegerField(default=0)),
                ('trace_heating_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('POWER_CHP', 'Power & Combined Heat/Power (CHP) Plant'), ('FUEL_STORAGE', 'Bulk & Day Tank Fuel Storage Depot'), ('HVAC_GLYCOL', 'Hydronic Glycol Thermal Loop / Heating'), ('WATER_INTAKE', 'Water Intake & Trace Heating Pipeline'), ('STRUCTURAL_HEALTH', 'Structural Health & Katabatic Vibration'), ('WEATHER', 'Automated Weather Station (AWS)')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('NOMINAL', 'Nominal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline')], default='NOMINAL', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('telemetry_metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='stations_twin.station')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('station', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_code', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Alarm'), ('EMERGENCY', 'Emergency Fail-Safe Triggered')], default='WARNING', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(help_text='Standard Operating Procedure (SOP) / Fail-safe action')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stations_twin.station')),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='stations_twin.subsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('metric_type', models.CharField(choices=[('temp', 'Temperature (°C)'), ('pressure', 'Pressure (bar / hPa)'), ('fuel_flow', 'Fuel Flow (L/h)'), ('kw_output', 'Electric Power (kW)'), ('vibration', 'Vibration Index (mm/s²)'), ('wind_speed', 'Wind Speed (km/h)'), ('status_flag', 'Binary State (0/1)'), ('level', 'Storage Level (%)'), ('flow_rate', 'Fluid Flow Rate (L/min)')], max_length=32)),
                ('unit', models.CharField(max_length=16)),
                ('safe_min', models.FloatField(blank=True, null=True)),
                ('safe_max', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='stations_twin.station')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='stations_twin.subsystem')),
            ],
            options={
                'ordering': ['subsystem', 'sensor_code'],
                'unique_together': {('station', 'sensor_code')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='stations_twin.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='stations_tw_sensor__fade9f_idx')],
            },
        ),
    ]
