# Generated by Django 6.1 on 2026-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations_twin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='code',
            field=models.CharField(choices=[('POWER_CHP', 'Power & Combined Heat/Power (CHP) Plant'), ('FUEL_STORAGE', 'Bulk & Day Tank Fuel Storage Depot'), ('HVAC_GLYCOL', 'Hydronic Glycol Thermal Loop / Heating'), ('WATER_INTAKE', 'Water Intake & Trace Heating Pipeline'), ('STRUCTURAL_HEALTH', 'Structural Health & Katabatic Vibration'), ('WEATHER', 'Automated Weather Station (AWS)'), ('BATTERY_STORAGE', 'Battery Energy Storage System (BESS) & Station UPS')], max_length=32),
        ),
    ]
